services:
  postgres:
    platform: linux/amd64
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  percona:
    platform: linux/amd64
    image: percona:8.0
    container_name: percona
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: app
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=root",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - percona_data:/var/lib/mysql

volumes:
  percona_data:
  postgres_data:
